const exp = [
  {
    title: "Carbon Copy",
    date: "Dec 2023",
    inicio: "Dec 2023",
    final: "Jan 2024",
    github: "https://github.com/pibelanzallamas/carbon-copy",
    youtube: "https://www.youtube.com/watch?v=bb8RomFHFdg",
    web: "http://carbon-copy-omega.vercel.app",
    desc: "A website developed primarily with React and Node.js that allows users to format, style a code snippet, and export it as an image. A website developed primarily with React and Node.js that allows users to format, style a code snippet, and export it as an image.",
    mainFeat: [
      {
        title: "Custom Styling",
        desc: "Format and style code snippets with your preferred colors and designs.",
      },
      {
        title: "Export as Image",
        desc: "Easily export your styled snippets as images for sharing.",
      },
      {
        title: "Favorites Management",
        desc: "Save and manage your favorite styles for quick reuse.",
      },
      {
        title: "Mobile Responsive",
        desc: "Enjoy a seamless experience across all devices.",
      },
    ],
    techs: [
      "NodeJs",
      "Express",
      "PostgreSQL",
      "Sequelize",
      "jsonwebtoken",
      "React",
      "Redux",
      "Mui",
      "Axios",
      "Sass",
      "react-syntax-highlighter",
      "react-notifications-component",
      "react-ace",
      "htmltocanvas",
      "downloadjs",
    ],
    photos: [
      "https://res.cloudinary.com/daynclfo8/image/upload/v1730124610/carbon_wk0osj.png",
    ],
    tools: ["Scrum Methology", "Dailys", "Figma", "Trello"],
    linksTools: ["TRELLO ", "FIGMA"],
  },
  {
    title: "House of Dev",
    date: "Dec 2023",
    inicio: "Ago 2023",
    final: "Sep 2023",
    github: "https://github.com/pibelanzallamas/house-of-dev-client-deploy",
    youtube: "https://www.youtube.com/watch?v=LiaV7xHjJmk",
    web: "https://house-of-dev-client.vercel.app",
    desc: "Website showcasing various properties in the city of Buenos Aires. It is an educational project from Plataforma 5, featuring a variety of functionalities. The website allows users to manage property listings (create, edit, delete) and schedule appointments with confirmation emails. It includes user account management and the ability to like properties. Advanced filtering options let users search by city, neighborhood, number of rooms, and more. Properties can be displayed based on specific rules, such as for sale or rent. The platform provides a seamless experience for browsing and interacting with properties.",
    photos: [
      "https://res.cloudinary.com/daynclfo8/image/upload/v1730124604/hod_vkfoxj.png",
    ],
    mainFeat: [
      {
        title: "Property Management",
        desc: "Create, edit, and delete property listings effortlessly.",
      },
      {
        title: "Advanced Search",
        desc: "Filter properties by city, neighborhood, rooms, and more.",
      },
      {
        title: "User Interaction",
        desc: "Like properties, schedule appointments, and receive email confirmations.",
      },
      {
        title: "Admin Mode",
        desc: "Cancel appointments and delete users from the admin dashboard.",
      },
    ],
    techs: [
      "NodeJs",
      "Express",
      "Sequelize",
      "Postgres",
      "nodemailer",
      "jsonwebtoken",
      "dotEnv",
      "Axios",
      "React",
      "Redux",
      "Mui",
      "Sass",
      "react-notifications-component",
      "styled-components",
      "nodemailer",
      "react-oauth2",
      "flatpickr",
    ],
    tools: ["Scrum Methology", "Dailys", "Figma", "Trello"],
    linksTools: ["Trello", "Figma"],
  },
  {
    title: "My Movie Crib",
    date: "Dec 2023",
    inicio: "Jul 2023",
    final: "Jul 2023",
    github: "https://github.com/pibelanzallamas",
    youtube: "https://www.youtube.com/watch?v=j-qgyoaeJN4",
    web: "https://my-movie-crib-front.vercel.app/",
    desc: "Website for looking for the leatest movies and search your favorites and save them. The website allows users to search for the latest releases and most popular movies, as well as filter by title using The Movie Database API. Built with React, Node.js, Express, Sequelize and Bulma. Users can register and log in",
    photos: [
      "https://res.cloudinary.com/daynclfo8/image/upload/v1732158213/crib2.png",
    ],
    mainFeat: [
      {
        title: "Movie Search",
        desc: "Search for the latest releases, popular movies, or by title.",
      },
      {
        title: "Favorite Movies",
        desc: "Add and manage your favorite movies for quick access.",
      },
      {
        title: "User Registration",
        desc: "Sign up and log in with email and password for personalized features.",
      },
      {
        title: "Movie Details",
        desc: "View detailed information about each movie, including ratings and descriptions.",
      },
    ],
    techs: [
      "NodeJs",
      "Express",
      "PostgreSQL",
      "Sequelize",
      "dotEnv",
      "jsonwebtoken",
      "React",
      "Redux",
      "Bulma",
      "Axios",
      "Sass",
    ],
    tools: ["Scrum Methology"],
  },
];

export default exp;
