const exp = [
  {
    title: "Carbon Copy",
    inicio: "Dec 2023",
    final: "Jan 2024",
    github: "https://github.com/brandoncastillodev/carbon-copy",
    youtube: "https://www.youtube.com/watch?v=bb8RomFHFdg",
    web: "http://carbon-copy-omega.vercel.app",
    desc: "A website built with React and Node.js that allows users to format and style code snippets with custom colors and designs, then export them as images. Users can save and manage their favorite styles for quick reuse and enjoy a fully responsive experience across all devices. Designed with an intuitive interface, it simplifies the process of creating and sharing visually appealing code snippets.",
    mainFeat: [
      {
        title: "Custom Styling",
        desc: "Format and style code snippets with your preferred colors and designs.",
      },
      {
        title: "Export as Image",
        desc: "Easily export your styled snippets as images for sharing.",
      },
      {
        title: "Favorites Management",
        desc: "Save and manage your favorite styles for quick reuse.",
      },
      {
        title: "Mobile Responsive",
        desc: "Enjoy a seamless experience across all devices.",
      },
    ],
    techs: [
      "NodeJs",
      "Express",
      "PostgreSQL",
      "Sequelize",
      "jsonwebtoken",
      "React",
      "Redux",
      "Mui",
      "Axios",
      "Sass",
      "react-syntax-highlighter",
      "react-notifications-component",
      "react-ace",
      "htmltocanvas",
      "downloadjs",
    ],
    photos: [
      "https://res.cloudinary.com/daynclfo8/image/upload/f_webp,q_80/v1732568128/carbon.png",
      "https://res.cloudinary.com/daynclfo8/image/upload/f_webp,q_80/v1732569610/carbon2.png",
      "https://res.cloudinary.com/daynclfo8/image/upload/f_webp,q_80/v1732569609/carbon3.png",
      "https://res.cloudinary.com/daynclfo8/image/upload/f_webp,q_80/v1732569609/carbon4.png",
    ],
    tools: ["Scrum Methodology"],
    linksTools: [
      {
        title: "Trello",
        link: "https://trello.com/invite/b/653037248cb51c4fa29a9071/ATTIfbd09fa0e24e0c5245823a38f310d4acD31E87F4/carbon-copy",
      },
      {
        title: "Figma",
        link: "https://www.figma.com/design/9mFFJxLH0ydY1XPal0tKy9/CarbonCopy?node-id=33-106&t=oHca0x4xOd34HpkH-1",
      },
    ],
  },
  {
    title: "House of Dev",
    inicio: "Ago 2023",
    final: "Sep 2023",
    github: "https://github.com/brandoncastillodev/house-of-dev-client-deploy",
    youtube: "https://www.youtube.com/watch?v=LiaV7xHjJmk",
    web: "https://house-of-dev-client.vercel.app",
    desc: "Website showcasing various properties in the city of Buenos Aires. It is an educational project from Plataforma 5, featuring a variety of functionalities. The website allows users to manage property listings (create, edit, delete) and schedule appointments with confirmation emails. It includes user account management and the ability to like properties. Advanced filtering options let users search by city, neighborhood, number of rooms, and more. Properties can be displayed based on specific rules, such as for sale or rent. The platform provides a seamless experience for browsing and interacting with properties.",
    photos: [
      "https://res.cloudinary.com/daynclfo8/image/upload/f_webp,q_80/v1732568386/house.png",
      "https://res.cloudinary.com/daynclfo8/image/upload/f_webp,q_80/v1732569056/house2.png",
      "https://res.cloudinary.com/daynclfo8/image/upload/f_webp,q_80/v1732569102/house3.png",
      "https://res.cloudinary.com/daynclfo8/image/upload/f_webp,q_80/v1732569107/house4.png",
    ],
    mainFeat: [
      {
        title: "Property Management",
        desc: "Create, edit, and delete property listings effortlessly.",
      },
      {
        title: "Advanced Search",
        desc: "Filter properties by city, neighborhood, rooms, and more.",
      },
      {
        title: "User Interaction",
        desc: "Like properties, schedule appointments, and receive email confirmations.",
      },
      {
        title: "Admin Mode",
        desc: "Cancel appointments and delete users from the admin dashboard.",
      },
    ],
    techs: [
      "NodeJs",
      "Express",
      "Sequelize",
      "Postgres",
      "nodemailer",
      "jsonwebtoken",
      "dotEnv",
      "Axios",
      "React",
      "Redux",
      "MUI",
      "Sass",
      "react-notifications-component",
      "styled-components",
      "nodemailer",
      "react-oauth2",
      "flatpickr",
    ],
    tools: ["Scrum Methodology", "Dailies"],
    linksTools: [
      {
        title: "Trello",
        link: "https://trello.com/invite/b/64dfc6c9543cee307423fb0f/ATTIfa1adb0194e4caae7238055fa4f0dab5B54EECB1/houseofdev",
      },
      {
        title: "Figma",
        link: "https://www.figma.com/design/EIQHhLYGbQIcoeNqQwustP/C%C3%A1psula-Integrador---House-of-Dev?node-id=0-1&t=Cgs2XdDDXqV3a2q4-1",
      },
    ],
  },
  {
    title: "My Movie Crib",
    date: "Jul 2023",
    inicio: "Jul 2023",
    final: "Jul 2023",
    github: "https://github.com/brandoncastillodev",
    youtube: "https://www.youtube.com/watch?v=j-qgyoaeJN4",
    web: "https://my-movie-crib.vercel.app/",
    desc: "Website for looking for the latest movies, search your favorites and save them. The website allows users to search for the latest releases and most popular movies, as well as filter by title using The Movie Database API. Built with React, Node.js, Express, Sequelize and Bulma. Users can register and log in.",
    photos: [
      // "https://res.cloudinary.com/daynclfo8/image/upload/f_webp,q_80/v1734134428/moviegif.gif",
      "https://res.cloudinary.com/daynclfo8/image/upload/f_webp,q_80/v1732567910/crib.png",
      "https://res.cloudinary.com/daynclfo8/image/upload/f_webp,q_80/v1732571274/crib2.png",
      "https://res.cloudinary.com/daynclfo8/image/upload/f_webp,q_80/v1732571148/crib3.png",
      "https://res.cloudinary.com/daynclfo8/image/upload/f_webp,q_80/v1732571168/crib4.png",
    ],
    mainFeat: [
      {
        title: "Movie Search",
        desc: "Search for the latest releases, popular movies, or by title.",
      },
      {
        title: "User Registration",
        desc: "Sign up and log in with email and password for personalized features.",
      },
      {
        title: "Favorite Movies",
        desc: "Add and manage your favorite movies for quick access.",
      },
      {
        title: "Movie Details",
        desc: "View detailed information about each movie, including websites and descriptions.",
      },
    ],
    techs: [
      "NodeJs",
      "Express",
      "PostgreSQL",
      "Sequelize",
      "dotEnv",
      "jsonwebtoken",
      "React",
      "Redux",
      "Axios",
      "Bulma",
      "Sass",
    ],
    tools: ["Scrum Methodology", "Solo Week"],
  },
];

export default exp;
