const works = [
  {
    title: "Calles Construction",
    date: "Jul 2024",
    incio: "Jun 2024",
    final: "Jul 2024",
    web: "https://calles-construction.vercel.app/",
    youtube: "https://www.youtube.com/watch?v=mOV8O6jPwC4",
    github: "https://github.com/pibelanzallamas/calles-construction",
    desc: "Website for showcasing the work of the construction company from NYC. The admin can receive emails, perform CRUD operations on jobs, descriptions, and images, and showcase the location and information of the company.",
    photos: [
      "https://res.cloudinary.com/daynclfo8/image/upload/v1730124619/calles_zngumy.png",
    ],
    mainFeat: [
      {
        title: "Custom Styling",
        desc: "Format and style code snippets with your preferred colors and designs.",
      },
      {
        title: "Export as Image",
        desc: "Easily export your styled snippets as images for sharing.",
      },
      {
        title: "Favorites Management",
        desc: "Save and manage your favorite styles for quick reuse.",
      },
      {
        title: "Mobile Responsive",
        desc: "Enjoy a seamless experience across all devices.",
      },
    ],
    techs: [
      "NodeJs",
      "Express",
      "PostgreSQL",
      "Sequelize",
      "jsonwebtoken",
      "React",
      "Redux",
      "Mui",
      "Axios",
      "Sass",
      "react-syntax-highlighter",
      "react-notifications-component",
      "react-ace",
      "htmltocanvas",
      "downloadjs",
    ],
    tools: ["Scrum Methology", "Dailys", "Figma", "Trello"],
    linksTools: ["TRELLO ", "FIGMA"],
  },
  {
    title: "Dreamer Paintings",
    final: "Apr 2024",
    inicio: "May 2024",
    web: "https://dreamer-paintings.vercel.app",
    youtube: "https://www.youtube.com/watch?v=onv0uQ7Y_1I",
    github: "https://github.com/pibelanzallamas/dreamers-paintings",
    desc: "Website for the abstract paintings of a talented artist from Buenos Aires, Argentina.",
    photos: [
      "https://res.cloudinary.com/daynclfo8/image/upload/v1730124626/dreamer_uz4hqg.png",
      "photo2",
      "photo3",
      "photo4",
      "photo5",
    ],
    mainFeat: [
      {
        title: "Custom Styling",
        desc: "Format and style code snippets with your preferred colors and designs.",
      },
      {
        title: "Export as Image",
        desc: "Easily export your styled snippets as images for sharing.",
      },
      {
        title: "Favorites Management",
        desc: "Save and manage your favorite styles for quick reuse.",
      },
      {
        title: "Mobile Responsive",
        desc: "Enjoy a seamless experience across all devices.",
      },
    ],
    techs: [
      "NodeJs",
      "Express",
      "PostgreSQL",
      "Sequelize",
      "jsonwebtoken",
      "React",
      "Redux",
      "Mui",
      "Axios",
      "Sass",
      "react-syntax-highlighter",
      "react-notifications-component",
      "react-ace",
      "htmltocanvas",
      "downloadjs",
    ],
    tools: ["Scrum Methology", "Dailys", "Figma", "Trello"],
    linksTools: ["TRELLO ", "FIGMA"],
  },
];

export default works;
