const works = [
  {
    title: "Calles Construction",
    incio: "Jun 2024",
    final: "Jul 2024",
    web: "https://calles-construction.vercel.app/",
    youtube: "https://www.youtube.com/watch?v=mOV8O6jPwC4",
    github: "https://github.com/pibelanzallamas/calles-construction",
    desc: "Website built with NodeJs and React, primarily used to showcase the work of Calles Construction, a construction company based in New Jersey. It provides detailed coverage of each project, organized into subcategories according to their respective fields. The site includes an exclusive image gallery, subdivided for better organization, and a section for submitting direct inquiries to the company. There is also an admin section for uploading and editing all projects, along with information about the company and its main location.",
    photos: [
      "https://res.cloudinary.com/daynclfo8/image/upload/v1730124619/calles_zngumy.png",
    ],
    mainFeat: [
      {
        title: "Custom Styling",
        desc: "Format and style code snippets with your preferred colors and designs.",
      },
      {
        title: "Export as Image",
        desc: "Easily export your styled snippets as images for sharing.",
      },
      {
        title: "Favorites Management",
        desc: "Save and manage your favorite styles for quick reuse.",
      },
      {
        title: "Mobile Responsive",
        desc: "Enjoy a seamless experience across all devices.",
      },
    ],
    techs: [
      "NodeJs",
      "Express",
      "PostgreSQL",
      "Sequelize",
      "jsonwebtoken",
      "React",
      "Redux",
      "Mui",
      "Axios",
      "Sass",
      "react-syntax-highlighter",
      "react-notifications-component",
      "react-ace",
      "htmltocanvas",
      "downloadjs",
    ],
    tools: ["Scrum Methology", "Dailys", "Figma", "Trello"],
    linksTools: ["TRELLO ", "FIGMA"],
  },
  {
    title: "Dreamer Paintings",
    final: "Apr 2024",
    inicio: "May 2024",
    web: "https://dreamer-paintings.vercel.app",
    youtube: "https://www.youtube.com/watch?v=onv0uQ7Y_1I",
    github: "https://github.com/pibelanzallamas/dreamers-paintings",
    desc: "Website for the abstract paintings of a talented artist from Buenos Aires, Argentina.",
    photos: [
      "https://res.cloudinary.com/daynclfo8/image/upload/v1730124626/dreamer_uz4hqg.png",
      "photo2",
      "photo3",
      "photo4",
      "photo5",
    ],
    mainFeat: [
      {
        title: "Custom Styling",
        desc: "Format and style code snippets with your preferred colors and designs.",
      },
      {
        title: "Export as Image",
        desc: "Easily export your styled snippets as images for sharing.",
      },
      {
        title: "Favorites Management",
        desc: "Save and manage your favorite styles for quick reuse.",
      },
      {
        title: "Mobile Responsive",
        desc: "Enjoy a seamless experience across all devices.",
      },
    ],
    techs: [
      "NodeJs",
      "Express",
      "PostgreSQL",
      "Sequelize",
      "jsonwebtoken",
      "React",
      "Redux",
      "Mui",
      "Axios",
      "Sass",
      "react-syntax-highlighter",
      "react-notifications-component",
      "react-ace",
      "htmltocanvas",
      "downloadjs",
    ],
    tools: ["Scrum Methology", "Dailys", "Figma", "Trello"],
    linksTools: ["TRELLO ", "FIGMA"],
  },
];

export default works;
